run:
  timeout: 5m
  skip-dirs:
    - constraints

linters:
  enable:
    # From Default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - unused

    # From Non-Default
    - errorlint
    - exportloopref
    - gci
    - gocritic
    - gofmt
    - gosec
    - nilerr
    - stylecheck
    - unconvert

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com)
